### ISSUE TITLE
Metallic Crops

### ISSUE THREAD

**Issue by Smrots** [ElectricBlue1/Pristine#1]
Metallic ores isn't rendered right and doesn't work (Can't smelt the ores)

**Comment by CluelessPhil** [comment]
Do you have an extra mod that enhance performance or add graphic details like shaders and texture packs. Do you have an extra mods that are affecting their models?

**Comment by Smrots** [comment]
No I tested this mod in the past with vanilla textures and it's the same thing.

**Comment by CluelessPhil** [comment]
Metallic Crops is being replaced with Croparia.
